name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest
      - name: Lint (ruff)
        run: |
          ruff check .
      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q
