name: Disabled CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: CI disabled
        run: echo "CI is disabled for this repository."
